### PR TITLE
Code comments and stylistic changes

### PR DESCRIPTION
**Pull request by spakin**
This revision incorporates a number of minor improvements to code and documentation quality.  The result passes [`go vet`](https://golang.org/cmd/vet/), [`misspell`](https://github.com/client9/misspell), and [`golint`](https://github.com/golang/lint).  To celebrate, the README file now includes a badge pointing to the [Go Report Card for golang-set](https://goreportcard.com/report/github.com/deckarep/golang-set).

### CODE REVIEW

**Comment by deckarep** [comment]
@spakin - fantastic! Thanks for your great and detailed work here. I am a huge fan of linters but have yet to run this project through my listing setup since I've only recently set them up.  You saved me the trouble so thanks for your momentum on this project!

**Comment by deckarep** [comment]
I'm not home right now but looks like this PR is complaining about merge commits. Perhaps you can revise your changes on your end and push force your branch.

**Comment by spakin** [comment]
> I'm not home right now but looks like this PR is complaining about merge commits. Perhaps you can revise your changes on your end and push force your branch.

Strange.  On my screen, GitHub says, "This branch has no conflicts with the base branch".  Is it possible you made some local changes that you haven't yet committed?  If not, what do you suggest I try doing?

**Comment by deckarep** [comment]
Hmmm...no, no local changes. It probably had to do with the way I last merged your PR. I'll see if I can sort it out tomorrow morning.  I definitely want to get this committed.

**Comment by spakin** [comment]
Are you using the command line or the GitHub interface to do the merge?  Perhaps try the other?

**Comment by spakin** [comment]
Hey, any news on merging request #47?  Let me know if there's something I should try on my end.

**Comment by deckarep** [comment]
@spakin - sorry for the radio silence on this. I had intended to get this done when we last talked and then I ended up starting a new job and getting a bit consumed so I haven't touched any personal projects in awhile.

I was able to manually merge things via the command-line and I think it's all good at this point.  Thank you again for the tidy work and the report card badge.  🥇

**Pull request merged**
