### PR TITLE
added basic json marshalling and unmarshalling

### LINKED ISSUE #24: add MarshalJSON / UnmarshalJSON
would be nice to be able to serialize to a json array and back.

### PR DESCRIPTION
**Pull request by Aorioli**
Resolves #24 

The problem that still remains is how to solve unmarshalling of non-primitive types.

### CODE REVIEW

**Comment by suntong** [comment]
Look quite good and comprehensive to me. Please merge. Thanks.

**Comment by deckarep** [comment]
@suntong - I will review it this evening and merge if it's all good.

**Comment by suntong** [comment]
Thank you both. 

@Aorioli, how to use it? 

I tried `mySet.MarshalJSON()`, but I got:

mySet.MarshalJSON undefined (type mapset.Set has no field or method MarshalJSON)

Do the `MarshalJSON` & `UnmarshalJSON` need to be defined in the type Set interface as well? 

Thx.

**Comment by suntong** [comment]
Works great. Thank you both, @Aorioli & @deckarep.

**Comment by deckarep** [comment]
It's merged!

**Pull request merged**
